"""Weekly recruiting stats report (replaces Grok Weekly bot for basics)."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from jobradar.db import Database


def build_report(db: Database | None = None) -> str:
    db = db or Database()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    jobs = db.count_jobs()
    apps = db.count_applications()
    lines = [
        f"# JobRadar weekly — {today}",
        "",
        "## Totals",
        f"- Jobs in SQLite: {jobs}",
        f"- Applications tracked: {apps}",
        "",
        "## Next actions",
        "- Check Notion **Needs Action** view (OA / Interview / Waiting)",
        "- Check Notion **Priority Active** for tier-1 companies",
        "- Run `python -m jobradar gmail-reorganize --days 30` if labels drift",
        "",
        "_Generated by `python -m jobradar weekly-report`. Grok Weekly bot optional for narrative._",
    ]
    return "\n".join(lines) + "\n"


def write_report(path: Path | None = None, db: Database | None = None) -> Path:
    db = db or Database()
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out = path or Path(f"docs/weekly/{today}.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_report(db=db))
    return out
