priority_companies:
  - OpenAI
  - Anthropic
  - Databricks
  - Snowflake
  - Nvidia
  - Scale AI
  - Perplexity
  - Meta
  - Google
  - Microsoft
  - Apple
  - Tesla
  - Palantir
  - Stripe
  - Figma
  - Roblox
  - Netflix
  - Jane Street
  - Hudson River Trading
  - Citadel
  - Ramp
  - Cursor
  - Anduril
  - xAI
